language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
jobs:
  include:
    # - stage: build base image
    #   script:
    #     - docker --version # print the version for logging
    #     - docker build -t nodebaseimage udagram-api/base_image/
    #     - docker tag nodebaseimage eedy/nodebaseimage:v1
    #   after_success:
    #     - echo "$DOCKERUB_TOKEN" | docker login --username "$DOCKER_NAME" --password-stdin
    #     - docker push eedy/nodebaseimage:v1

    - stage: build backend-api
      script:
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker build -t udagram-api-user ./udagram-api-user
        - docker tag udagram-api-feed khoihuynh1312/udagram-api-feed:v1
        - docker tag udagram-api-user khoihuynh1312/udagram-api-user:v1
      after_success:
        - echo "$DOCKERUB_TOKEN" | docker login --username "$DOCKER_NAME" --password-stdin
        - docker push khoihuynh1312/udagram-api-feed:v1
        - docker push khoihuynh1312/udagram-api-user:v1

    - stage: build reverse-proxy
      language: bash 
      script:
        - docker build -t reverseproxy udeagram-reverseproxy/
        - docker tag reverseproxy khoihuynh1312/reverseproxy:latest
      after_success:
        - echo "$DOCKERUB_TOKEN" | docker login -u "$DOCKER_NAME" --password-stdin
        - docker push khoihuynh1312/reverseproxy:latest
    
    - stage: build frontend image
      script:
        - docker build -t udagram-frontend udagram-frontend/
        - docker tag udagram-frontend khoihuynh1312/udagram-frontend:latest
      after_success:
        - echo "$DOCKERUB_TOKEN" | docker login -u "$DOCKER_NAME" --password-stdin
        - docker push khoihuynh1312/udagram-frontend:latest 