apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
  selector:
    service: udagram-frontend